### ISSUE TITLE
Error while trying to run the build

### ISSUE THREAD

**Issue by dang-1234** [howdyai/botkit-starter-ciscospark#11]
Tried remixing this on glitch and a local install and I see this error.
Any clues ?

TypeError: Cannot read property 'map' of undefined
at child.handleHttpError (I:\Dan\node\botkit-starter-ciscospark-master\node_modules@ciscospark\spark-core\dist\lib\batcher.js:208:53)
at \node\botkit-starter-ciscospark-master\node_modules@ciscospark\spark-core\dist\lib\batcher.js:142:25
at process._tickCallback (internal/process/next_tick.js:109:7)
(node:9724) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 17): TypeError: Cannot read property 'map' of undefined

**Comment by peterswimm** [comment]
Confirmed the bug, escalating internally with the Botkit team.

**Comment by peterswimm** [comment]
This should now be fixed:

https://github.com/howdyai/botkit/issues/948
